//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danil_AutoServiceRul.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public string ProductPhoto { get; set; }
        public string ProductManufacturer { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<int> ProductDiscountAmount { get; set; }
        public Nullable<int> ProductQuantityInStock { get; set; }
        public string ProductStatus { get; set; }
        public string Unit { get; set; }
        public string MaxDiscountAmount { get; set; }
        public string Supplier { get; set; }
        public string CountInPack { get; set; }
        public string MinCount { get; set; }
    
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }

        public string Background
        {
            get
            {
                if (this.ProductDiscountAmount > 15)
                    return "#7fff00";
                return "#fff";
            }
        }
        public string CostWithDiscount
        {
            get
            { 
                if (int.Parse(this.MaxDiscountAmount) > 0)
                {
                    var costWithDiscount = Convert.ToDouble(this.ProductCost) - Convert.ToDouble(this.ProductCost) * Convert.ToDouble(this.ProductDiscountAmount / 100.00);
                    return costWithDiscount.ToString();
                }
                else return this.ProductCost.ToString();
            }
        }
        public string ImgPath
        {
            get
            {
                var path = "C:\\Users\\portm\\Desktop\\danil\\Danil_AutoServiceRul\\Resources\\" + this.ProductPhoto;
                return path;
            }
        }
    }
}
